### ISSUE TITLE
Can't use card transition within TabBarController [Not Fixed]

### ISSUE THREAD

**Issue by tarastomchuk** [appssemble/appstore-card-transition#8] opened 2020-02-14 13:23 UTC
After implementing fix suggested here - [399705d](https://github.com/appssemble/appstore-card-transition/commit/399705d0573a2485f0d8ad6ec2dc27cc0fe000d1) still facing same issue if presenting from CollectionView Cell inside TabBarController. I'm using Xcode 11.3.1, Swift 5.1, iOS 13.3
 
![image](https://user-images.githubusercontent.com/35869411/74535154-e7df6c80-4f3d-11ea-81f0-97d2b8f65aed.png)

**Comment by Abhi-philips** [comment] 2020-03-02 11:52
Same issue I am also facing with tab bar

**Comment by fl034** [comment] 2020-03-02 12:13
I'm using this workaround

```
// Somehow the custom modal presentation transitioning uses the tab bar controller so this needs to be done as extension of the Tab Bar Controller.
extension UITabBarController: CardsViewController {
    public var transitionDelegate: CardTransitioningDelegate? {
        // Not needed for now
        get { nil }
        set {}
    }
}
```

**Comment by Abhi-philips** [comment] 2020-03-02 12:25
CardTransitioningDelegate is not there demo project,Could you please tell me where you are using

**Comment by chelemen-razvan** [comment] 2020-03-03 06:34
Can you do a demo that reproduces this issue? I seems to work fine for me.

**Comment by Abhi-philips** [comment] 2020-03-03 06:47
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/Project/Pods/appstore-card-transition/AppstoreTransition/AppstoreTransition/PresentCardAnimator.swift, line 90

**Comment by Abhi-philips** [comment] 2020-03-03 06:49
app is crashing in PresentCardanimator line number 90  while using tabbar . I am using xcode11.3.1 and swift 5.0

**Comment by chelemen-razvan** [comment] 2020-03-03 06:55
I cannot reproduce this. Can you provide a demo project?

**Comment by quyentrinh** [comment] 2020-03-15 08:38
Same issue. 
UITabbarController -> UINavigationControler -> **FromViewController(root)** -> **ToViewController**
Could not cast value of type 'UITabBarController' to 'AppstoreTransition.CardsViewController'.
![Screen Shot 2020-03-15 at 3 36 29 PM](https://user-images.githubusercontent.com/17674733/76698219-d58a5700-66d2-11ea-9aec-c84948317132.png)

**Comment by chelemen-razvan** [comment] 2020-03-15 09:06
Guys please provide a demo project if you want this fixed, I cannot produce it.

**Comment by quyentrinh** [comment] 2020-03-15 10:07
My demo project.
[https://github.com/quyentrinh/appstore-card-transition-demo](url)
From the example project, I just changed a bit.
In Main.storyboard, ViewController was embed in UINavigationController and UITabbarController.
Hope this helps you.

**Comment by chelemen-razvan** [comment] 2020-03-16 07:06
Fixed in https://github.com/appssemble/appstore-card-transition/releases/tag/1.0.4

**Closed as completed** 2020-03-17 09:47 UTC
